name: rebook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  qr_code_scanner: ^1.0.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.4.0
  flutter_secure_storage: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/marcus-loke-WQJvWU_HZFo-unsplash.jpg
   - assets/details.jpg
   - assets/price.jpg
   - assets/verify.jpg
   - assets/view.jpg
   - assets/coverphoto.jpeg
   - assets/profile.jpg
   - assets/Error.gif
   - assets/Success.gif
   - assets/Animation.gif
  
   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
